# Generated by Django 5.2.9 on 2026-09-23 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='meals/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='meal_price_gte_0')],
            },
        ),
        migrations.CreateModel(
            name='MealSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('capacity', models.PositiveIntegerField()),
                ('reservation_open_at', models.DateTimeField()),
                ('reservation_close_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='meals.meal')),
            ],
            options={
                'ordering': ['date', 'meal__name'],
                'indexes': [models.Index(fields=['date'], name='meal_schedule_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('meal', 'date'), name='unique_meal_schedule_per_day'), models.CheckConstraint(condition=models.Q(('capacity__gte', 0)), name='meal_schedule_capacity_gte_0'), models.CheckConstraint(condition=models.Q(('reservation_open_at__lte', models.F('reservation_close_at'))), name='meal_schedule_open_before_close')],
            },
        ),
    ]
