# Generated by Django 5.2.9 on 2026-09-23 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meals', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('reservation_date', models.DateField(db_index=True, editable=False)),
                ('status', models.CharField(choices=[('RESERVED', 'Reserved'), ('CANCELLED', 'Cancelled'), ('USED', 'Used'), ('NO_SHOW', 'No Show')], db_index=True, default='RESERVED', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('meal_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='meals.mealschedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='students.student')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='reservation_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'RESERVED')), fields=('student', 'reservation_date'), name='unique_active_student_reservation_per_day')],
            },
        ),
    ]
